-- MySQL Script generated by MySQL Workbench
-- Sun Sep  3 19:25:40 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Taskursion
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Taskursion
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Taskursion` DEFAULT CHARACTER SET utf8 ;
USE `Taskursion` ;

-- -----------------------------------------------------
-- Table `Taskursion`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Taskursion`.`user` ;

CREATE TABLE IF NOT EXISTS `Taskursion`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(255) NOT NULL,
  `user_email` VARCHAR(255) NOT NULL,
  `user_pass_hash` CHAR(255) NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_email_UNIQUE` (`user_email` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `Taskursion`.`user`
-- -----------------------------------------------------
START TRANSACTION;
USE `Taskursion`;
INSERT INTO `Taskursion`.`user` (`user_id`, `user_name`, `user_email`, `user_pass_hash`) VALUES (1, 'Test User', 'test@email.com', 'someLong$tring');

COMMIT;

